version: '3'
services:
  web_server:
    build: ./web_server
    ports:
      - "3000:3000"
    command: ["python", "server.py"]

  socket_server:
    build: ./socket_server
    ports:
      - "5000:5000"
    command: ["python", "app/socket_server.py"]