version: '3'
services:
  web_server:
    build: ./web_server
    ports:
      - "3000:3000"
    command: ["python", "server.py"]
    depends_on:
      - mongodb
  socket_server:
    build: ./socket_server
    ports:
      - "5000:5000"
    command: ["python", "/app/socket_server.py"]
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /storage/:/storage/